main:
	g++ -std=c++11 -pthread -I./inlcude -L./usr/lib64  main.cpp  -lboost_system -lboost_filesystem -lboost_serialization -lboost_thread
	g++ -std=c++11 -pthread -I./inlcude -L./usr/lib64  main_client.cpp  -lboost_system -lboost_filesystem -lboost_serialization -lboost_thread -o x_client
clean:
	rm -rf x_*
