// Copyright (c) 2014 Baidu.com, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "error_code.h"

namespace hdcs {
namespace networking {

#define MAKE_CASE(name) case name: return (#name)

const char* RpcErrorCodeToString(int error_code)
{
    switch(error_code)
    {
        MAKE_CASE(HDCS_NETWORK_SUCCESS);

        MAKE_CASE(HDCS_NETWORK_ERROR_PARSE_REQUEST_MESSAGE);
        MAKE_CASE(HDCS_NETWORK_ERROR_PARSE_RESPONSE_MESSAGE);
        MAKE_CASE(HDCS_NETWORK_ERROR_UNCOMPRESS_MESSAGE);
        MAKE_CASE(HDCS_NETWORK_ERROR_COMPRESS_TYPE);
        MAKE_CASE(HDCS_NETWORK_ERROR_NOT_SPECIFY_METHOD_NAME);
        MAKE_CASE(HDCS_NETWORK_ERROR_PARSE_METHOD_NAME);
        MAKE_CASE(HDCS_NETWORK_ERROR_FOUND_SERVICE);
        MAKE_CASE(HDCS_NETWORK_ERROR_FOUND_METHOD);
        MAKE_CASE(HDCS_NETWORK_ERROR_CHANNEL_BROKEN);
        MAKE_CASE(HDCS_NETWORK_ERROR_CONNECTION_CLOSED);
        MAKE_CASE(HDCS_NETWORK_ERROR_REQUEST_TIMEOUT);
        MAKE_CASE(HDCS_NETWORK_ERROR_REQUEST_CANCELED);
        MAKE_CASE(HDCS_NETWORK_ERROR_SERVER_UNAVAILABLE);
        MAKE_CASE(HDCS_NETWORK_ERROR_SERVER_UNREACHABLE);
        MAKE_CASE(HDCS_NETWORK_ERROR_SERVER_SHUTDOWN);
        MAKE_CASE(HDCS_NETWORK_ERROR_SEND_BUFFER_FULL);
        MAKE_CASE(HDCS_NETWORK_ERROR_SERIALIZE_REQUEST);
        MAKE_CASE(HDCS_NETWORK_ERROR_SERIALIZE_RESPONSE);
        MAKE_CASE(HDCS_NETWORK_ERROR_RESOLVE_ADDRESS);
        MAKE_CASE(HDCS_NETWORK_ERROR_CREATE_STREAM);
        MAKE_CASE(HDCS_NETWORK_ERROR_NOT_IN_RUNNING);
        MAKE_CASE(HDCS_NETWORK_ERROR_SERVER_BUSY);

        MAKE_CASE(HDCS_NETWORK_ERROR_TOO_MANY_OPEN_FILES);

        MAKE_CASE(HDCS_NETWORK_ERROR_UNKNOWN);
        MAKE_CASE(HDCS_NETWORK_ERROR_FROM_USER);
    }
    return "HDCS_NETWORK_ERROR_UNDEFINED";
}

} 
}
